name: Sync Fork

on:
  schedule:
    # 使用 UTC 时间，每小时的第 0 分钟执行（即整点执行）
    - cron: '0 * * * *'  # 星号表示每小时执行
  workflow_dispatch:     # 保留手动触发功能

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置 Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/celin1286/xiaosa

      - name: 获取上游更新
        run: git fetch upstream

      - name: 合并并推送
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
